# 專案資訊
site_name: Pino Wiki
site_url: https://pinxian53.github.io/wiki
site_dir: site

# 儲存庫
#repo_name: Pino Wiki
#repo_url: https://github.com/PinXian53/wiki

# 版權宣告
copyright: Copyright Pino 2025

# 主題
theme:
  name: material
  language: zh-Hant
  font:
    text: Google Sans
    code: Roboto Mono
  logo: assets/logo.png
  favicon: assets/logo.png
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      primary: white
      accent: white
      toggle:
        icon: material/brightness-7
        name: 切換至深色模式
    - scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/brightness-4
        name: 切換至淺色模式
  features:
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.path
    - navigation.top
    - toc.follow

# 擴充功能
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      dedent_subsections: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - toc:
      permalink: true

# 外掛
plugins:
  - search

# 導覽
nav:
  - 首頁: index.md
  - MkDocs + Material:
      - mkdocs-material/index.md
      - Get Started: mkdocs-material/get-started.md
      - Github Action: mkdocs-material/github-action.md
      - Advanced: mkdocs-material/advanced.md
